backend:
  name: git-gateway
  branch: main

# These lines should *not* be indented
# 

media_folder: "public/assets/blog" 
public_folder: "assets/blog"

# collections
collections:
 - name: "blog"
  label: "Blog" #label is used in the UI
  folder: "src/blog"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #controls filename
  fields:
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Description", name: "description", widget: "string"}
    - { label: "Author", name: "author", widget: "string"}
    - { label: "Date", name: "date", widget: "datetime"}
    - { label: "Tags", name: "tags", widget: "list", default: ["post"]}
    - { label: "Featured Image", name: "image", widget: "string"}
    - { label: "Image caption", name: "imageAlt", widget: "string"}
    - { label: "Body", name: "body", widget: "markdown"}